# SPDX-FileCopyrightText: Copyright (c) 2022-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: sa
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  sa:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo make install
      - run: make sa
